In [20]:
import numpy as np


# Basic Numpy Array

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [9]:
a[1]

2

In [11]:
a[-1]

4

In [13]:
a[0:]

array([1, 2, 3, 4])

In [16]:
a[[0,2,-1]]

array([1, 3, 4])

# How to check the data types of the array


In [25]:
x = np.array([1,2,3,4])
x.dtype

dtype('int32')

In [27]:
y = np.array([2.,3.,4.,5.])
y.dtype

dtype('float64')

In [29]:
z = np.array(['a','b','c'])
z.dtype

dtype('<U1')

# Dimensions and shapes  

In [31]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
a.shape

(3, 4)

In [40]:
a.ndim

2

In [43]:
a.size

12

# Indexing and slicing of matrics

In [45]:
a[1]

array([5, 6, 7, 8])

In [47]:
a[0:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
a[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [52]:
# if you want to change the values same as the list
a[1] = np.array([10])
a

array([[ 1,  2,  3,  4],
       [10, 10, 10, 10],
       [ 9, 10, 11, 12]])

# Summary of Statistics 

In [56]:
a.sum()

92

In [58]:
a.mean()

7.666666666666667

In [60]:
a.std()

3.7712361663282534

In [67]:
x=a.sum(axis=0)
print("The sum the colums",x)

y=a.sum(axis=1)
print("The sum the rows",y)

The sum the colums [20 22 24 26]
The sum the rows [10 40 42]


In [69]:
x=a.mean(axis=0)
print("The mean the colums",x)

y=a.mean(axis=1)
print("The mean the rows",y)

The mean the colums [6.66666667 7.33333333 8.         8.66666667]
The mean the rows [ 2.5 10.  10.5]


In [70]:
x=a.std(axis=0)
print("The Standard Daviation the colums",x)

y=a.std(axis=1)
print("The Standard Daviation the rows",y)

The Standard Daviation the colums [4.02768199 3.77123617 3.55902608 3.39934634]
The Standard Daviation the rows [1.11803399 0.         1.11803399]
